# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='ptaraUsers',
        ),
    ]
