# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0002_auto_20180227_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptarausers',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ptarausers',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
