# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0004_auto_20180227_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptarausers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='ptarausers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ptarausers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
