# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0005_auto_20180228_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptarausers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
