# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0006_auto_20180228_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptarausers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ptarausers',
            name='password',
        ),
    ]
