# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptaraback', '0007_auto_20180305_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptarausers',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
