"""projectTARA URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.authtoken.views import obtain_auth_token

from projectTARA.routers import HybridRouter
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from ptaraback.views import *
from rest_framework.routers import DefaultRouter

#router = HybridRouter()
#router = HybridRouter()
#router = DefaultRouter()

#register REST API endpoints with DRF router
#router.register(r'register', UserCreateViewSet, base_name="register")
#router.register(r'login', UserLoginView, base_name="login")
#router.add_api_view(r'register', url(r'^register/$', UserViewSet.as_view({'get': 'list'}), name=r"reg"))



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^token-auth/', obtain_auth_token),
    url(r'^register/', UserCreateView.as_view(), name='register'),
    url(r'^login/', UserLoginView.as_view(), name='login'),
    #url(r'^login/$', UserViewSet.as_view(), name='register'),
    #url(r'^api/', include(router.urls, namespace='api')),
# root view of our REST api, generated by Django REST Framework's router
    #url(r'^api/', include(router.urls, namespace='api')),
]

#urlpatterns = format_suffix_patterns(urlpatterns)
#urlpatterns = router.urls
